### ISSUE TITLE
Poner link a logo de ESPOL

### ISSUE THREAD

**Issue by cmonsalvec** [lejacome/TranEspol#6]
Favor enlazar el logo de la ESPOL a su página web: www.espol.edu.ec

Actualmente está el logo al final de la página de administración, pero no hay un link al sitio web de espol

**Comment by lejacome** [comment]
Estimado,
de acuerdo a su solicitud, el requerimiento esta fuera de nuestro alcance ya que en la aplicación web embebimos el sitio web de TransEspol para mostrarlo en la aplicación, es decir le corresponderia a Transespol modificarlo en su sitio web

**Comment by cmonsalvec** [comment]
Se acepta el resultado

**Comment by jjjohncedeno** [comment]
Listo, procederemos a cerrar el ticket.
